<?xml version="1.0"?>
<package format="3">
  <name>simple_planning_interface</name>
  <version>1.0.0</version>
  <description>The simple_planning_interface package</description>

  <maintainer email="phxhuy@gmail.com">Huy Pham</maintainer>

  <license>BSD</license>
  <url type="website">https://github.com/phxhuy/simple_planning_interface</url>

  <author >Huy Pham</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>interactive_markers</depend>
  <depend>visualization_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>